version: '3.8'

services:
  minecraft:
    image: docker.io/itzg/minecraft-server:latest
    container_name: neo-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "https://github.com/onexbash/onexcraft/releases/latest/download/onexcraft.mrpack"
      MEMORY: "6G"
      TZ: "UTC"
    volumes:
      - ./data:/data:Z
    restart: unless-stopped
