version: '3.8'

services:
  # -- Minecraft Server -- #
  minecraft:
    image: docker.io/itzg/minecraft-server:latest
    container_name: onexcraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE" # Has to be "TRUE" for accepting the minecraft terms & services
      # VERSION: "1.21.1"
      MOTD: "Femboy Paradise" # Server Log-In message
      # LEVEL: "world" # Use an existing world on the server (see: https://minecraft.wiki/w/Server.properties#level-name)
      DIFFICULTY: "easy"
      TYPE: "MODRINTH"
      MODRINTH_MODPACK: "https://github.com/onexbash/onexcraft/releases/latest/download/onexcraft.mrpack"
      MODRINTH_FORCE_SYNCHRONIZE: "TRUE"
      RESOURCE_PACK: "https://github.com/onexbash/onexcraft/releases/download/resourcepack/PureBDcraft_64x-onexcraft.zip"
      RESOURCE_PACK_SHA1: "149c12be571b2839c1444eea952d2d612b3e3e45" # checksum of the resource pack zip-file
      RESOURCE_PACK_ENFORCE: "FALSE" # whether to kick players who decline the resource pack installation
      HARDCORE: false
      # ICON: 
      ENABLE_WHITELIST: false
      # WHITELIST: "yunginlavih" # comma seperated list of usernames
      # WHITELIST_FILE # path to a whitelist json file
      MEMORY: "6G"
      TZ: "UTC"
      LOG_LEVEL: "info" # [trace, debug, info, warn, error]
      OPS: |
        yunginlavih
      EXISTING_OPS_FILE: SYNCHRONIZE
      ENABLE_RCON: true
      RCON_PASSWORD: "${RCON_PASSWORD}" # put in .env
    volumes:
      - ./data:/data:z
    restart: unless-stopped
  # -- Minecraft Server Backups -- #
  backup:
    image: docker.io/itzg/mc-backup:latest
    container_name: onexcraft-backup
    depends_on:
      - minecraft
    environment:
      BACKUP_METHOD: "restic"        # dedupes across the 2wk retention, way smaller than tar
      BACKUP_INTERVAL: "4h"
      PRUNE_BACKUPS_DAYS: "14"
      RCON_HOST: minecraft
      RCON_PASSWORD: "${RCON_PASSWORD}" # put in .env
      RESTIC_PASSWORD: "${RESTIC_PASSWORD}"   # put in .env
      RESTIC_REPOSITORY: "/backups/restic_repo"
      INITIAL_DELAY: "2m"
    volumes:
      - ./data:/data:z
      - ./backups:/backups:Z
    restart: unless-stopped
