name = "onexcraft"
author = "onexbash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96314428d69d7e09a7425f4d9b3496f8e03bccdebccfee6e77b8e6d2e9a71e51"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
