name = "onexcraft"
author = "onexbash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bff93f1b14e58bcb2e9e55bc3a8ac1633546cb57774e818d7ff30cfbfe57f543"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
