name = "onexcraft"
author = "onexbash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e817f0da878b657d9cbf5cf6f8fecb46eed8e2fb11000fd08493a2ac5dab9ec"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
