name: Modpack onexcraft Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Export mrpack
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          packwiz mr export -o pack.mrpack

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: pack.mrpack
          generate_release_notes: true
